### ISSUE TITLE
Allow configuring different WebClient.Builder beans (not shared) for each @RetrofitClient instance?

### ISSUE THREAD

**Issue by dante-ricalde** [spring-cloud-incubator/spring-cloud-square#25]
**Describe the bug**
Hi guys, @OlgaMaciaszek, 
at the docs about Retrofit with WebClient you can find information about how to configure a `WebClient.Builder` to be used under the hood for the Retrofit clients as shown by the following configuration:

```
@Configuration
@EnableRetrofitClients
class OkHttpClientConfig {

@Bean
@LoadBalanced
public WebClient.Builder okHttpClientBuilder() {
    return WebClient.builder();
    }
}
```
As you can notice, this configuration shows us how to use a shared `WebClient.Builder` to be used for all the `@RetrofitClient` instances.

I have the following question:
**how Can I configure a different `WebClient.Builder` for each `@RetrofitClient` instance?**
Imagine I have two client instances:
```
@RetrofitClient(name = "Api1Client")
public interface Api1Client {
    @GET("/")
    Mono<String> hello();
}
```
and 
```
@RetrofitClient(name = "Api2Client")
public interface Api2Client {
    @GET("/")
    Mono<String> hello();
}
```

and I want to configure different timeouts and other properties for each client:  
for example for Api1Client I want to configure:
- connectTimeout=300
- readTimeout=1200
- writeTimeout=800
- 1 interceptor: Interceptor1
- A proxyConfiguration:
```
 httpClient.tcpConfiguration(tcpClient -> tcpClient
                .proxy(proxy -> proxy
                    .type(ProxyProvider.Proxy.HTTP)
                    .host("ourproxy.com")
                    .port(8080)
```

and for client Api2Client I want to configure:
- connectTimeout=600
- readTimeout=3000
- writeTimeout=2000
- 2 interceptors: Interceptor2,Interceptor3

**How can I configure 2 different WebClient Builders, one for Api1Client and other for Api2Client?
Is there a way to specify a different `WebClient.Builder` to be used in the `@RetrofitClient`?**

Please, could you help me with these questions?
Thanks and Regards.

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by OlgaMaciaszek** [comment]
Hi @dante-ricalde - it's currently not supported, but I think we might add it. Working on it now - should have a PR ready tomorrow.

**Comment by dante-ricalde** [comment]
> Hi @dante-ricalde - it's currently not supported, but I think we might add it. Working on it now - should have a PR ready tomorrow.

Thank you so much @OlgaMaciaszek 
I appreciate your help to add that feature
Regards.
