### ISSUE TITLE
@POST with @Body doesn't work using @RetrofitClient with WebClient

### ISSUE THREAD

**Issue by dante-ricalde** [spring-cloud-incubator/spring-cloud-square#26]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

Hi guys, @OlgaMaciaszek
I am trying to use @RetrofitClient with WebClient using the @Body annotation for the body, but it is not working.

I am trying with the following Retrofit Client:

```
@RetrofitClient(name = "HelloServer", url = "http://localhost:7111", configuration = HelloClientConfiguration.class)
public interface HelloClient {

    @GET("/")
    Mono<String> hello();

    @Headers({"Content-Type: application/json"})
    @POST("/card")
    Mono<Card> create(@Body Card card);
}
```

I have the following questions:

**I would like to know if you have implemented the CallAdapterFactory or ConverterFactory so that the @Body works serializing the object to be set as the request body?** We are using the version 0.4.0-M1 of spring-cloud-square-retrofit and the serializing of the Body is not working.

**We would like to know if you know about this and how We can do to solve this problem: maybe adding a specific configuration or  waiting for the next version of spring-cloud-square?**

I am looking forward to hearing from you!
**Important: If you need help regarding to this issue, please let me know how I can help you.**

Best Regards!

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by jarpz** [comment]
Hi, any update about this issue? we are facing the same error.

**Comment by OlgaMaciaszek** [comment]
Hi, @dante-ricalde @jarpz it works with our tests and we cannot reproduce the issue: https://github.com/spring-cloud-incubator/spring-cloud-square/blob/05b1c9bbcb89ffc689d7ae04cb994d9ce0765cf7/spring-cloud-square-retrofit/src/test/java/org/springframework/cloud/square/retrofit/RetrofitClientUrlTests.java#L114-L122. I can verify it further, but I would need you to provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by jarpz** [comment]
Hi @OlgaMaciaszek I opened a PR https://github.com/spring-cloud-incubator/spring-cloud-square/pull/28

With a test with WebClient as HTTP client where payloads (RequestBody) are not sent.

I can see in your test that you are using OkHttpClient. 

Did you check with spring webclient?

Regards.

**Comment by OlgaMaciaszek** [comment]
Thanks, will take a look at this.

**Comment by OlgaMaciaszek** [comment]
The bug is there. Will fix it.
