### ISSUE TITLE
Release plan dates?

### ISSUE THREAD

**Issue by jarpz** [spring-cloud-incubator/spring-cloud-square#31]
Hi.

This project will be releasing this year (2021)? or where do you plan to release it? we would like to use it in production environments. We already use Retrofit + Okhttp client on production environments. 

Regards.

**Comment by GHKevins** [comment]
@OlgaMaciaszek spring-cloud-square will replace openfeign in the future?

When cat it be used in the production environment?

**Comment by OlgaMaciaszek** [comment]
It can be used in production now if you're using Spring Cloud `2021.x`, but only as a temporary solution. It will be replaced by [Spring Interface Clients](https://docs.spring.io/spring-framework/docs/6.0.0-SNAPSHOT/reference/html/integration.html#rest-http-interface) starting with Spring Cloud `2022.x`.
