### ISSUE TITLE
Retrofit primary bean as configuration

### ISSUE THREAD

**Issue by mcmatws** [spring-cloud-incubator/spring-cloud-square#33]
It would be nice to have the capability to mark generated beans as non-primary.
This would allow for the applications to be able to automatically wire a local implementation of the service and, if non is present, fallback to the Retrofit provider.

This is really useful when building microservice architectures that can also work as modulites, where the client and the server-side implementation may or may not co-exist in the same application depending on the setup.

It might be as simple as changing:
AbstractRetrofitClientsRegistrar#registerRetrofitClient
_beanDefinition.setPrimary(true);_ --> _beanDefinition.setPrimary( «config-based-boolean» );_

As it is right now, if the application contains an implementation of the service a retrofit client is always loaded regardless.

Cheers

**Comment by OlgaMaciaszek** [comment]
@mcmatws Thanks for submitting the issue. Makes sense.
